import type { Metadata } from "next";
import { 
  Space_Grotesk, 
  Syne, 
  Inter, 
  JetBrains_Mono 
} from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Analytics } from "@vercel/analytics/next";
import { CustomCursor } from "@/components/CustomCursor";

const spaceGrotesk = Space_Grotesk({ 
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "| RUPAK GHOSH |",
  description: "Generated by create next app",
  // icons: {
  //   icon: [
  //     {
  //       media: '(prefers-color-scheme: dark)',
  //       url: '/Images/user.png',
  //       href: '/Images/user.png',
  //     },
  //   ],
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        spaceGrotesk.variable,
        syne.variable,
        inter.variable,
        jetbrainsMono.variable,
        "bg-black text-white font-body selection:bg-primary/30 selection:text-primary"
      )}>
        <CustomCursor />
        <Navbar />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
